### healthcheck.GetResultByOperationID
GET http://{{baseURL}}/api/v1/healthcheck/history
Content-Type: application/json

{
  "login_name": "{{login_name}}"
}

### healthcheck.GetResultByOperationID
GET http://{{baseURL}}/api/v1/healthcheck/result/{{result_id}}
Accept: application/json

### healthcheck.Check
POST http://{{baseURL}}/api/v1/healthcheck/check
Content-Type: application/json

{
    "server_id": {{mysql_server_id}},
    "start_time": "{{startTime}}",
    "end_time": "{{endTime}}",
    "step": "{{step}}",
    "login_name": "{{login_name}}"
}

### healthcheck.CheckByHostInfo
POST http://{{baseURL}}/api/v1/healthcheck/check/host-info
Content-Type: application/json

{
    "host_ip": "{{mysql_host_ip}}",
    "port_num": {{mysql_port_num}},
    "start_time": "{{startTime}}",
    "end_time": "{{endTime}}",
    "step": "{{step}}",
    "login_name": "{{login_name}}"
}

### healthcheck.ReviewAccuracy
POST http://{{baseURL}}/api/v1/healthcheck/review
Content-Type: application/json

{
    "operation_id": {{operation_id}},
    "review": {{review}}
}