### healthcheck.GetResultByOperationID
GET http://{{baseURL}}/api/v1/healthcheck/history
Content-Type: application/json

{
  "login_name": "zhangs"
}

### healthcheck.GetResultByOperationID
GET http://{{baseURL}}/api/v1/healthcheck/result/16
Accept: application/json

### healthcheck.Check
POST http://{{baseURL}}/api/v1/healthcheck/check
Content-Type: application/json

{
    "server_id": 1,
    "start_time": "{{startTime}}",
    "end_time": "{{endTime}}",
    "step": "{{step}}",
    "login_name": "zhangs"
}

### healthcheck.CheckByHostInfo
POST http://{{baseURL}}/api/v1/healthcheck/check/host-info
Content-Type: application/json

{
    "host_ip": "192.168.137.11",
    "port_num": 3306,
    "start_time": "{{startTime}}",
    "end_time": "{{endTime}}",
    "step": "{{step}}",
    "login_name": "zhangs"
}

### healthcheck.ReviewAccuracy
POST http://{{baseURL}}/api/v1/healthcheck/review
Content-Type: application/json

{
    "operation_id": 1,
    "review": 1
}