### get tables by db id
GET http://{{baseURL}}/api/v1/metadata/table/db
Content-Type: : application/json

{
    "token": "{{token}}",
    "db_id": {{db_id}},
    "login_name": "{{login_name}}"
}

### get table statistics by db id and table name
GET http://{{baseURL}}/api/v1/metadata/table/statistic/db
Content-Type: : application/json

{
    "token": "{{token}}",
    "db_id": {{db_id}},
    "table_name": "{{table_name}}",
    "login_name": "{{login_name}}"
}

### get table statistics by host info and db name and table name
GET http://{{baseURL}}/api/v1/metadata/table/statistic/host-info-db
Content-Type: : application/json

{
    "token": "{{token}}",
    "host_ip": "{{mysql_host_ip}}",
    "port_num": {{mysql_port_num}},
    "db_name": "{{db_name}}",
    "table_name": "{{table_name}}",
    "login_name": "{{login_name}}"
}

### analyze table by db id and table name
POST http://{{baseURL}}/api/v1/metadata/table/analyze/db
Content-Type: application/json

{
    "token": "{{token}}",
    "db_id": {{db_id}},
    "table_name": "{{table_name}}",
    "login_name": "{{login_name}}"
}

### analyze table by host info and db name and table name
POST http://{{baseURL}}/api/v1/metadata/table/analyze/host-info
Content-Type: application/json

{
    "token": "{{token}}",
    "host_ip": "{{mysql_host_ip}}",
    "port_num": {{mysql_port_num}},
    "db_name": "{{db_name}}",
    "table_name": "{{table_name}}",
    "login_name": "{{login_name}}"
}