GET http://{{baseURL}}/api/v1/metadata/user
Accept: application/json

{
    "token": "{{token}}"
}

### GetUserByName
GET http://{{baseURL}}/api/v1/metadata/user/user-name
Accept: application/json

{
    "user_name":"{{user_name}}",
    "token": "{{token}}"
}

### GetUserByID
GET http://{{baseURL}}/api/v1/metadata/user/get
Accept: application/json

{
    "id":"{{user_id}}",
    "token": "{{token}}"
}

### GetUserByEmployeeID
GET http://{{baseURL}}/api/v1/metadata/user/employee-id
Accept: application/json

{
    "employee_id":"{{employee_id}}",
    "token": "{{token}}"
}

### GetUserByAccountName
GET http://{{baseURL}}/api/v1/metadata/user/account-name
Accept: application/json

{
    "account_name":"{{account_name}}",
    "token": "{{token}}"
}

### GetUserByAccountNameOrEmployeeID
GET http://{{baseURL}}/api/v1/metadata/user/login-name
Accept: application/json

{
    # "login_name":"{{account_name}}",
    "login_name":"{{employee_id}}",
    "token": "{{token}}"
}

### GetUserByEmail
GET http://{{baseURL}}/api/v1/metadata/user/email
Accept: application/json

{
    "email":"{{email}}",
    "token": "{{token}}"
}

### GetUserByTelephone
GET http://{{baseURL}}/api/v1/metadata/user/telephone
Accept: application/json

{
    "telephone":"{{telephone}}",
    "token": "{{token}}"
}

### GetUserByMobile
GET http://{{baseURL}}/api/v1/metadata/user/mobile
Accept: application/json

{
    "mobile":"{{mobile}}",
    "token": "{{token}}"
}

### AddUser
POST http://{{baseURL}}/api/v1/metadata/user
Content-Type: application/json

{
  "token": "{{token}}", 
  "department_name": "{{department_name}}",
  "employee_id": "{{employee_id}}", 
  "telephone": "{{telephone}}",
  "role": "{{role}}",
  "del_flag": "{{del_flag}}",
  "user_name": "{{user_name}}",
  "account_name": "{{account_name}}",
  "email": "{{email}}",
  "mobile": "{{mobile}}" 
}

### UpdateUserByID
POST http://{{baseURL}}/api/v1/metadata/user/update
Content-Type: application/json

{
  "id":"{{user_id}}",
  "token": "{{token}}",
  "department_name": "{{department_name}}",
  "employee_id": "{{employee_id}}", 
  "telephone": "{{telephone}}",
  "role": "{{role}}",
  "del_flag": "{{del_flag}}",
  "user_name": "{{user_name}}",
  "account_name": "{{account_name}}",
  "email": "{{email}}",
  "mobile": "{{mobile}}" 
}

### DeleteUserByID
POST http://{{baseURL}}/api/v1/metadata/user/delete
Content-Type: application/json

{
    "id":"{{user_id}}",
    "token": "{{token}}"
}

### get all apps by id
GET http://{{baseURL}}/api/v1/metadata/user/app
Accept: application/json

{
    "id":"{{user_id}}",
    "token": "{{token}}"
}

### get all dbs by id
GET http://{{baseURL}}/api/v1/metadata/user/db
Accept: application/json

{
    "id":"{{user_id}}",
    "token": "{{token}}"
}

### get all middlewareclusters by id
GET http://{{baseURL}}/api/v1/metadata/user/middleware-cluster
Accept: application/json

{
    "id":"{{user_id}}",
    "token": "{{token}}"
}

### get all mysqlclusters by id
GET http://{{baseURL}}/api/v1/metadata/user/mysql-cluster
Accept: application/json

{
    "id":"{{user_id}}",
    "token": "{{token}}"
}

### get all mysqlservers by id
GET http://{{baseURL}}/api/v1/metadata/user/all-mysql-server
Accept: application/json

{
    "id":"{{user_id}}",
    "token": "{{token}}"
}

