### get all databases
GET http://{{baseURL}}/api/v1/metadata/db
Content-Type: application/json

{
    "token": "{{token}}"
}

### get all databases by env_id
GET http://{{baseURL}}/api/v1/metadata/db/env
Content-Type: application/json

{
    "token": "{{token}}",
    "env_id": {{env_id}}
}

### get database by id
GET http://{{baseURL}}/api/v1/metadata/db/get
Content-Type: application/json

{
    "token": "{{token}}",
    "id": {{db_id}}
}

### get database by db name and cluster info
GET http://{{baseURL}}/api/v1/metadata/db/name-and-cluster-info
Content-Type: application/json

{
    "token": "{{token}}",
    "db_name": {{db_name}},
    "cluster_id": {{mysql_cluster_id}},
    "cluster_type": {{mysql_cluster_type}}
}

### get database by db name and host info
GET http://{{baseURL}}/api/v1/metadata/db/name-and-host-info
Content-Type: application/json

{
    "token": "{{token}}",
    "db_name": {{db_name}},
    "host_ip": {{mysql_host_ip}},
    "port_num": {{mysql_port_num}}
}

### get databases by host info
GET http://{{baseURL}}/api/v1/metadata/db/host-info
Content-Type: application/json

{
    "token": "{{token}}",
    "host_ip": {{mysql_host_ip}},
    "port_num": {{mysql_port_num}}
}

### get all apps by id
GET http://{{baseURL}}/api/v1/metadata/db/app
Content-Type: application/json

{
    "token": "{{token}}",
    "id": {{db_id}}
}

### get mysql cluster by id
GET http://{{baseURL}}/api/v1/metadata/db/mysql-cluster
Content-Type: application/json

{
    "token": "{{token}}",
    "id": {{db_id}}
}

### get app user by id
GET http://{{baseURL}}/api/v1/metadata/db/app-user
Content-Type: application/json

{
    "token": "{{token}}",
    "id": {{db_id}}
}

### get db user by id
GET http://{{baseURL}}/api/v1/metadata/db/db-user
Content-Type: application/json

{
    "token": "{{token}}",
    "id": {{db_id}}
}

### get all user by id
GET http://{{baseURL}}/api/v1/metadata/db/all-user
Content-Type: application/json

{
    "token": "{{token}}",
    "id": {{db_id}}
}

### add new database
POST http://{{baseURL}}/api/v1/metadata/db
Content-Type: application/json

{
    "token": "{{token}}",
    "db_name": {{db_name}},
    "cluster_id": {{mysql_cluster_id}},
    "cluster_type": {{mysql_cluster_type}},
    "env_id": {{env_id}}
}

### update database by id
POST http://{{baseURL}}/api/v1/metadata/db/update
Content-Type: application/json

{
    "token": "{{token}}",
    "id": {{db_id}},
    "db_name": "new_db",
    "cluster_id": "192.168.10.219",
    "cluster_type": 1,
    "env_id": 1,
    "del_flag": 0
}

### delete database by id
POST http://{{baseURL}}/api/v1/metadata/db/delete
Content-Type: application/json

{
    "token": "{{token}}",
    "id": {{db_id}}
}

### add new app by id
POST http://{{baseURL}}/api/v1/metadata/db/add-app
Content-Type: application/json

{
    "token": "{{token}}",
    "id": {{db_id}},
    "app_id": 3
}

### delete app by id
POST http://{{baseURL}}/api/v1/metadata/db/delete-app
Content-Type: application/json

{
    "token": "{{token}}",
    "id": {{db_id}},
    "app_id": 3
}

### add new user by id
POST http://{{baseURL}}/api/v1/metadata/db/add-user
Content-Type: application/json

{
    "token": "{{token}}",
    "id": {{db_id}},
    "user_id": 3
}

### delete user by id
POST http://{{baseURL}}/api/v1/metadata/db/delete-user
Content-Type: application/json

{
    "token": "{{token}}",
    "id": {{db_id}},
    "user_id": 3
}
