### get all resource roles
GET http://{{baseURL}}/api/v1/metadata/resource-role
Content-Type: application/json

{
    "token": "{{token}}"
}

### get resource role by id
GET http://{{baseURL}}/api/v1/metadata/resource-role/get
Content-Type: application/json

{
    "token": "{{token}}",
    "id" : {{resource_role_id}}
}

### get resource role by role uuid
GET http://{{baseURL}}/api/v1/metadata/resource-role/role-uuid
Content-Type: application/json

{
    "token": "{{token}}",
    "role_uuid": "{{resource_role_uuid}}"
}


### get master mysql server of resource role
GET http://{{baseURL}}/api/v1/metadata/resource-role/resource_group
Content-Type: application/json

{
    "token": "{{token}}",
    "id": {{resource_role_id}}
}

### get resource role users
GET http://{{baseURL}}/api/v1/metadata/resource-role/user
Content-Type: application/json

{
    "token": "{{token}}",
    "id": {{resource_role_id}}
}


### get all users
GET http://{{baseURL}}/api/v1/metadata/resource-role/user/role-uuid
Content-Type: application/json

{
    "token": "{{token}}",
    "role_uuid": "{{resource_role_uuid}}"
}

### add user map
POST http://{{baseURL}}/api/v1/metadata/resource-role/add-user
Content-Type: application/json

{
    "token": "{{token}}",
    "id": {{resource_role_id}},
    "user_id": {{user_id}}
}


### delete user map
POST http://{{baseURL}}/api/v1/metadata/resource-role/delete-user
Content-Type: application/json

{
    "token": "{{token}}",
    "id": {{resource_role_id}},
    "user_id": {{user_id}}
}


### add new resource role
POST http://{{baseURL}}/api/v1/metadata/resource-role
Content-Type: application/json

{
    "token": "{{token}}",
    "role_uuid": "new_test_role_uuid",
    "role_name": "new_test_role",
    "resource_group_id":{{resource_group_id}}
}


### update resource role by id
POST http://{{baseURL}}/api/v1/metadata/resource-role/update
Content-Type: application/json

{
    "token": "{{token}}",
    "id": 25,
    "role_uuid": "update_test_role_id",
    "role_name": "update_test_role",
    "del_flag": 0
}

### delete resource role by id
POST http://{{baseURL}}/api/v1/metadata/resource-role/delete
Content-Type: application/json

{
    "token": "{{token}}",
    "id": 25
}