### get all middleware server
POST http://{{baseURL}}/api/v1/metadata/middleware-server/all
Content-Type: application/json

{
    "token": "{{token}}"
}

### get middleware server by cluster id
POST http://{{baseURL}}/api/v1/metadata/middleware-server/cluster-id
Content-Type: application/json

{
    "token": "{{token}}",
    "cluster_id": {{middleware_cluster_id}}
}

### get middleware server by id
POST http://{{baseURL}}/api/v1/metadata/middleware-server/id
Content-Type: application/json

{
    "token": "{{token}}",
    "id": {{middleware_server_id}}
}

### get middleware server by host info
POST http://{{baseURL}}/api/v1/metadata/middleware-server/host-info
Content-Type: application/json

{
    "token": "{{token}}",
    "host_ip": "{{middleware_host_ip}}",
    "port_num": {{middleware_port_num}}
}

### add new middleware server
POST http://{{baseURL}}/api/v1/metadata/middleware-server/add
Content-Type: application/json

{
    "token": "{{token}}",
    "cluster_id": 1,
    "server_name": "new_middleware_server",
    "middleware_role": 1,
    "host_ip": "192.168.137.11",
    "port_num": 33062
}

### update middleware-server by id
POST http://{{baseURL}}/api/v1/metadata/middleware-server/update
Content-Type: application/json

{
    "token": "{{token}}",
    "id": {{new_middleware_server_id}},
    "server_name": "update_middeware_server"
}

### delete middleware-server by id
POST http://{{baseURL}}/api/v1/metadata/middleware-server/delete
Content-Type: application/json

{
    "token": "{{token}}",
    "id": {{new_middleware_server_id}}
}