### get all monitor systems
GET http://{{baseURL}}/api/v1/metadata/monitor-system
Content-Type: application/json

{
    "token": "{{token}}"
}

### get all monitor systems by env_id
GET http://{{baseURL}}/api/v1/metadata/monitor-system/env
Content-Type: application/json

{
    "token": "{{token}}",
    "env_id": {{env_id}}
}

### get monitor system by id
GET http://{{baseURL}}/api/v1/metadata/monitor-system/get
Content-Type: application/json

{
    "token": "{{token}}",
    "id": {{monitor_system_id}}
}

### get all monitor systems by host-info
GET http://{{baseURL}}/api/v1/metadata/monitor-system
Content-Type: application/json

{
    "token": "{{token}}",
    "host_ip": "{{monitor_system_host_ip}}",
    "port_num": {{monitor_system_port_num}}
}

### add new monitor system
POST http://{{baseURL}}/api/v1/metadata/monitor-system
Content-Type: application/json

{
    "token": "{{token}}",
    "system_name": "new_monitor_system",
    "system_type":2,
    "host_ip": "192.168.137.11",
    "port_num": 8080,
    "port_num_slow": 9000,
    "base_url": "/prometheus",
    "env_id": 1
}

### update monitor system by id
POST http://{{baseURL}}/api/v1/metadata/monitor-system/update
Content-Type: application/json

{
    "token": "{{token}}",
    "id": {{new_monitor_system_id}},
    "system_name": "update_monitor_system",
    "system_type":3,
    "host_ip": "192.168.137.11",
    "port_num": 8081,
    "port_num_slow": 9001,
    "base_url": "/prometheus",
    "env_id": 1,
    "del_flag": 0
}

### delete monitor system by id
POST http://{{baseURL}}/api/v1/metadata/monitor-system/delete
Content-Type: application/json

{
    "token": "{{token}}",
    "id": {{new_monitor_system_id}}
}