GET http://{{baseURL}}/api/v1/metadata/user
Content-Type: application/json

{
    "token": "{{token}}"
}

### GetUserByName
GET http://{{baseURL}}/api/v1/metadata/user/user-name
Content-Type: application/json

{
    "token": "{{token}}",
    "user_name":"{{user_name}}"
}

### GetUserByID
GET http://{{baseURL}}/api/v1/metadata/user/get
Content-Type: application/json

{
    "token": "{{token}}",
    "id":"{{user_id}}"
}

### GetUserByEmployeeID
GET http://{{baseURL}}/api/v1/metadata/user/employee-id
Content-Type: application/json

{
    "token": "{{token}}",
    "employee_id":"{{employee_id}}"
}

### GetUserByAccountName
GET http://{{baseURL}}/api/v1/metadata/user/account-name
Content-Type: application/json

{
    "token": "{{token}}",
    "account_name":"{{account_name}}"
}

### GetUserByAccountNameOrEmployeeID
GET http://{{baseURL}}/api/v1/metadata/user/login-name
Content-Type: application/json

{
    "token": "{{token}}",
    # "login_name":"{{account_name}}"
    "login_name":"{{employee_id}}"
}

### GetUserByEmail
GET http://{{baseURL}}/api/v1/metadata/user/email
Content-Type: application/json

{
    "token": "{{token}}",
    "email":"{{email}}"
}

### GetUserByTelephone
GET http://{{baseURL}}/api/v1/metadata/user/telephone
Content-Type: application/json

{
    "token": "{{token}}",
    "telephone":"{{telephone}}"
}

### GetUserByMobile
GET http://{{baseURL}}/api/v1/metadata/user/mobile
Content-Type: application/json

{
    "token": "{{token}}",
    "mobile":"{{mobile}}"
}

### AddUser
POST http://{{baseURL}}/api/v1/metadata/user
Content-Type: application/json

{
  "token": "{{token}}", 
  "department_name": "{{department_name}}",
  "employee_id": "{{employee_id}}", 
  "telephone": "{{telephone}}",
  "role": "{{role}}",
  "del_flag": "{{del_flag}}",
  "user_name": "{{user_name}}",
  "account_name": "{{account_name}}",
  "email": "{{email}}",
  "mobile": "{{mobile}}" 
}

### UpdateUserByID
POST http://{{baseURL}}/api/v1/metadata/user/update
Content-Type: application/json

{
  "token": "{{token}}",
  "id":"{{user_id}}",
  "department_name": "{{department_name}}",
  "employee_id": "{{employee_id}}", 
  "telephone": "{{telephone}}",
  "role": "{{role}}",
  "del_flag": "{{del_flag}}",
  "user_name": "{{user_name}}",
  "account_name": "{{account_name}}",
  "email": "{{email}}",
  "mobile": "{{mobile}}" 
}

### DeleteUserByID
POST http://{{baseURL}}/api/v1/metadata/user/delete
Content-Type: application/json

{
    "token": "{{token}}",
    "id":"{{user_id}}"
}

### get all apps by id
GET http://{{baseURL}}/api/v1/metadata/user/app
Content-Type: application/json

{
    "token": "{{token}}",
    "id":"{{user_id}}"
}

### get all dbs by id
GET http://{{baseURL}}/api/v1/metadata/user/db
Content-Type: application/json

{
    "token": "{{token}}",
    "id":"{{user_id}}"
}

### get all middlewareclusters by id
GET http://{{baseURL}}/api/v1/metadata/user/middleware-cluster
Content-Type: application/json

{
    "token": "{{token}}",
    "id":"{{user_id}}"
}

### get all mysqlclusters by id
GET http://{{baseURL}}/api/v1/metadata/user/mysql-cluster
Content-Type: application/json

{
    "token": "{{token}}",
    "id":"{{user_id}}"
}

### get all mysqlservers by id
GET http://{{baseURL}}/api/v1/metadata/user/all-mysql-server
Content-Type: application/json

{
    "token": "{{token}}",
    "id":"{{user_id}}"
}

