### get all middleware cluster
GET http://{{baseURL}}/api/v1/metadata/middleware-cluster
Content-Type: application/json

{
    "token": "{{token}}"
}

### get middleware cluster by env_id
GET http://{{baseURL}}/api/v1/metadata/middleware-cluster/env
Content-Type: application/json

{
    "token": "{{token}}",
    "env_id": {{env_id}}
}

### get middleware cluster by id
GET http://{{baseURL}}/api/v1/metadata/middleware-cluster/get
Content-Type: application/json

{
    "token": "{{token}}",
    "id": {{middleware_cluster_id}}
}

### get middleware cluster by name
GET http://{{baseURL}}/api/v1/metadata/middleware-cluster/cluster-name
Content-Type: application/json

{
    "token": "{{token}}",
    "cluster_name": "{{middleware_cluster_name}}"
}

### get middleware server list by cluster id
GET http://{{baseURL}}/api/v1/metadata/middleware-cluster/middleware-server
Content-Type: application/json

{
    "token": "{{token}}",
    "id": {{middleware_cluster_id}}
}

### get user list by middleware cluster id
GET http://{{baseURL}}/api/v1/metadata/middleware-cluster/user
Content-Type: application/json

{
    "token": "{{token}}",
    "id": {{middleware_cluster_id}}
}

### add new middleware cluster
POST http://{{baseURL}}/api/v1/metadata/middleware-cluster
Content-Type: application/json

{
    "token": "{{token}}",
    "cluster_name": "new_middleware_cluster",
    "env_id": {{env_id}}
}

### update middleware cluster by id
POST http://{{baseURL}}/api/v1/metadata/middleware-cluster/update
Content-Type: application/json

{
    "token": "{{token}}",
    "id": {{new_middleware_cluster_id}},
    "cluster_name": "update_middleware_cluster"
}

### add a new map of middleware cluster and user in the middleware
POST http://{{baseURL}}/api/v1/metadata/middleware-cluster/add-user
Content-Type: application/json

{
    "token": "{{token}}",
    "id": {{new_middleware_cluster_id}},
    "user_id": {{user_id}}
}

### delete a map of middleware cluster and user in the middleware
POST http://{{baseURL}}/api/v1/metadata/middleware-cluster/delete-user
Content-Type: application/json

{
    "token": "{{token}}",
    "id": {{new_middleware_cluster_id}},
    "user_id": {{user_id}}
}

### delete middleware cluster by id
POST http://{{baseURL}}/api/v1/metadata/middleware-cluster/delete
Content-Type: application/json

{
    "token": "{{token}}",
    "id": {{new_middleware_cluster_id}}
}