### get all databases
GET http://{{baseURL}}/api/v1/metadata/db
Content-Type: application/json

### get all databases by env_id
GET http://{{baseURL}}/api/v1/metadata/db/env/1
Content-Type: application/json

### get database by id
GET http://{{baseURL}}/api/v1/metadata/db/get/1
Content-Type: application/json

### get all apps by id
GET http://{{baseURL}}/api/v1/metadata/db/app/1
Content-Type: application/json

### add new database
POST http://{{baseURL}}/api/v1/metadata/db
Content-Type: application/json

{"db_name": "new_db", "cluster_id": 1, "cluster_type": 1, "env_id": 1}

### update database by id
POST http://{{baseURL}}/api/v1/metadata/db/update/1
Content-Type: application/json

{"db_name": "update_db"}

### update database by id
POST http://{{baseURL}}/api/v1/metadata/db/update/1
Content-Type: application/json

{"db_name": "pmm_test"}

### delete database by id
POST http://{{baseURL}}/api/v1/metadata/db/delete/13
Content-Type: application/json

### add new app by id
POST http://{{baseURL}}/api/v1/metadata/db/add-app/1
Content-Type: application/json

{"app_id": 2}

### delete app by id
POST http://{{baseURL}}/api/v1/metadata/db/delete-app/1
Content-Type: application/json

{"app_id": 2}

### add new user by id
POST http://{{baseURL}}/api/v1/metadata/db/add-user/1
Content-Type: application/json

{"user_id": 4}

### delete user by id
POST http://{{baseURL}}/api/v1/metadata/db/delete-user/1
Content-Type: application/json

{"user_id": 4}
