### get tables by db id
GET http://{{baseURL}}/api/v1/metadata/table/db/4
Accept: application/json

{
    "token": "{{token}}",
    "login_name": "yc_admin"
}

### get table statistics by db id and table name
GET http://{{baseURL}}/api/v1/metadata/table/statistic/db-table
Accept: application/json

{
    "token": "{{token}}",
    "db_id": 4,
    "table_name": "test",
    "login_name": "yc_admin"
}

### get table statistics by host info and db name and table name
GET http://{{baseURL}}/api/v1/metadata/table/statistic/host-info-db-table
Accept: application/json

{
    "token": "{{token}}",
    "host_ip": "127.0.0.1",
    "port_num": 3306,
    "db_name": "das",
    "table_name": "t_meta_mysql_cluster_info",
    "login_name": "yc_admin"
}

### analyze table by db id and table name
POST http://{{baseURL}}/api/v1/metadata/table/analyze/db
Content-Type: application/json

{
    "token": "{{token}}",
    "db_id": 4,
    "table_name": "test",
    "login_name": "yc_guest"
}

### analyze table by host info and db name and table name
POST http://{{baseURL}}/api/v1/metadata/table/analyze/host-info
Content-Type: application/json

{
    "token": "{{token}}",
    "host_ip": "127.0.0.1",
    "port_num": 3306,
    "db_name": "yc",
    "table_name": "test",
    "login_name": "yc_admin"
}