### metadata.GetApp
GET http://{{baseURL}}/api/v1/metadata/app 
Accept: application/json

{
    "token": "{{token}}"
}

### metadata.GetAppByID
GET http://{{baseURL}}/api/v1/metadata/app/get 
Accept: application/json

{
    "id":"{{app_id}}",
    "token": "{{token}}",
}

### metadata.GetAppByName
GET http://{{baseURL}}/api/v1/metadata/app/app-name 
Accept: application/json

{
    "app_name":"{{app_name}}",
    "token": "{{token}}"
}

### metadata.GetDBsByAppID
GET http://{{baseURL}}/api/v1/metadata/app/db
Accept: application/json

{
    "id":"{{app_id}}",
    "token": "{{token}}"
}

### metadata.GetUsersByAppID
GET http://{{baseURL}}/api/v1/metadata/app/user
Accept: application/json

{
    "id":"{{app_id}}",
    "token": "{{token}}"
}

### metadata.AddApp
POST http://{{baseURL}}/api/v1/metadata/app 
Content-Type: application/json

{
    "token": "{{token}}",
    "app_name": "{{app_name}}",
    "level":"{{level}}",
    "owner_id":"{{owner_id}}"
}

### metadata.UpdateAppByID
POST http://{{baseURL}}/api/v1/metadata/app/update
Content-Type: application/json

{
    "id":"{{app_id}}",
    "token": "{{token}}",
    "app_name": "{{app_name}}",
    "level":"{{level}}",
    "owner_id":":{{owner_id}}"
}

### metadata.DeleteAppByID
POST http://{{baseURL}}/api/v1/metadata/app/delete 

{
    "id":"{{app_id}}",
    "token": "{{token}}"
}

### metadata.AppAddDB
POST http://{{baseURL}}/api/v1/metadata/app/add-db
Content-Type: application/json

{
    "id":"{{app_id}}",
    "token": "{{token}}",
    "db_id":"{{db_id}}"
}

### metadata.AppAddUser
POST http://{{baseURL}}/api/v1/metadata/app/add-user
Content-Type: application/json

{
    "id":"{{app_id}}",
    "token": "{{token}}",
    "user_id":"{{user_id}}"
}


### metadata.AppDeleteDB
POST http://{{baseURL}}/api/v1/metadata/app/delete-db
Content-Type: application/json

{
    "id":"{{app_id}}",
    "token": "{{token}}",
    "db_id":"{{db_id}}"
}

### metadata.AppDeleteUser
POST http://{{baseURL}}/api/v1/metadata/app/delete-user
Content-Type: application/json

{
    "id":"{{app_id}}",
    "token": "{{token}}",
    "user_id":"{{user_id}}"
}