@baseURL = localhost:6090
@token = f3171bd9-beec-11ec-acc0-000c291d6734
@env_id = 1
@resource_role_id = 1
@resource_role_uuid = resource-role-pmm1
@user_id = 14

### get all resource roles
GET http://{{baseURL}}/api/v1/metadata/resource-role
Content-Type: application/json

{
    "token": "{{token}}"
}

### get resource role by id
GET http://{{baseURL}}/api/v1/metadata/resource-role/get
Content-Type: application/json

{
    "token": "{{token}}",
    "id" : {{resource_role_id}}
}

### get resource role by role uuid
GET http://{{baseURL}}/api/v1/metadata/resource-role/role-uuid
Content-Type: application/json

{
    "token": "{{token}}",
    "role_uuid": "{{resource_role_uuid}}"
}


### get master mysql server of resource role
GET http://{{baseURL}}/api/v1/metadata/resource-role/resource_group
Content-Type: application/json

{
    "token": "{{token}}",
    "id": {{resource_role_id}}
}

### get resource role users
GET http://{{baseURL}}/api/v1/metadata/resource-role/user
Content-Type: application/json

{
    "token": "{{token}}",
    "id": {{resource_role_id}}
}


### get all users
GET http://{{baseURL}}/api/v1/metadata/resource-role/user/role-uuid
Content-Type: application/json

{
    "token": "{{token}}",
    "role-uuid": "{{resource_role_uuid}}"
}

### add user map
POST http://{{baseURL}}/api/v1/metadata/resource-role/add-user
Content-Type: application/json

{
    "token": "{{token}}",
    "id": {{resource_role_id}},
    "user_id": {{user_id}}
}


### delete user map
POST http://{{baseURL}}/api/v1/metadata/resource-role/delete-user
Content-Type: application/json

{
    "token": "{{token}}",
    "id": {{resource_role_id}},
    "user_id": {{user_id}}
}


### add new resource role
POST http://{{baseURL}}/api/v1/metadata/resource-role
Content-Type: application/json

{
    "token": "{{token}}",
    "role_uuid": "{{resource_role_uuid}}",
    "role_name": "api_test",
}


### update resource role by id
POST http://{{baseURL}}/api/v1/metadata/resource-role/update
Content-Type: application/json

{
    "token": "{{token}}",
    "id": 3,
    "role_uuid": "{{resource_role_uuid}}",
    "role_name": "api_test",
    "del_flag": 0
}

### delete resource role by id
POST http://{{baseURL}}/api/v1/metadata/resource-role/delete
Content-Type: application/json

{
    "token": "{{token}}",
    "id": 3
}