@baseURL = 127.0.0.1:6090
@token = 
### GetUser
GET http://{{baseURL}}/api/v1/metadata/user
Accept: application/json

{
    "token": "{{token}}"
}

### GetUserByName
GET http://{{baseURL}}/api/v1/metadata/user/user-name
Accept: application/json

{
    "token": "{{token}}",
    "user_name":"tester"
}

### GetUserByID
GET http://{{baseURL}}/api/v1/metadata/user/get
Accept: application/json

{
    "token": "{{token}}",
    "id":14
}

### GetUserByEmployeeID
GET http://{{baseURL}}/api/v1/metadata/user/employee-id
Accept: application/json

{
    "token": "{{token}}",
    "employee_id":"employee_id2"
}

### GetUserByAccountName
GET http://{{baseURL}}/api/v1/metadata/user/account-name
Accept: application/json

{
    "token": "{{token}}",
    "account_name":"account_name2"
}

### GetUserByAccountNameOrEmployeeID
GET http://{{baseURL}}/api/v1/metadata/user/login-name
Accept: application/json

{
    "token": "{{token}}",
    # "login_name":"testemployee_id"
    "login_name":"testaccount_name"
}

### GetUserByEmail
GET http://{{baseURL}}/api/v1/metadata/user/email
Accept: application/json

{
    "token": "{{token}}",
    "email":"test@email.com"
}

### GetUserByTelephone
GET http://{{baseURL}}/api/v1/metadata/user/telephone
Accept: application/json

{
    "token": "{{token}}",
    "telephone":"telephone"
}

### GetUserByMobile
GET http://{{baseURL}}/api/v1/metadata/user/mobile
Accept: application/json

{
    "token": "{{token}}",
    "mobile":"mobile"
}

### AddUser
POST http://{{baseURL}}/api/v1/metadata/user
Content-Type: application/json

{
  "token": "{{token}}", 
  "department_name": "testdepartment_name",
  "employee_id": "testemployee_id", 
  "telephone": "testtelephone",
  "role": 2,
  "del_flag": 0,
  "user_name": "testuser_name",
  "account_name": "testaccount_name",
  "email": "testemail",
  "mobile": "testmobile" 
}

### UpdateUserByID
POST http://{{baseURL}}/api/v1/metadata/user/update
Content-Type: application/json

{
  "token": "{{token}}",
  "id":17,
  "department_name": "department_name",
  "employee_id": "employee_id2", 
  "telephone": "telephone",
  "role": 2,
  "del_flag": 0,
  "user_name": "user_name2",
  "account_name": "account_name2",
  "email": "emai2l",
  "mobile": "mobile" 
}

### DeleteUserByID
POST http://{{baseURL}}/api/v1/metadata/user/delete
Content-Type: application/json

{
    "token": "{{token}}",
    "id":17
}

### get all apps by id
GET http://{{baseURL}}/api/v1/metadata/user/app
Accept: application/json

{
    "token": "{{token}}",
    "id":14
}

### get all dbs by id
GET http://{{baseURL}}/api/v1/metadata/user/db
Accept: application/json

{
    "token": "{{token}}",
    "id":1
}

### get all middlewareclusters by id
GET http://{{baseURL}}/api/v1/metadata/user/middleware-cluster
Accept: application/json

{
    "token": "{{token}}",
    "id":1
}

### get all mysqlclusters by id
GET http://{{baseURL}}/api/v1/metadata/user/mysql-cluster
Accept: application/json

{
    "token": "{{token}}",
    "id":1
}

### get all mysqlservers by id
GET http://{{baseURL}}/api/v1/metadata/user/all-mysql-server
Accept: application/json

{
    "token": "{{token}}",
    "id":1
}

