@baseURL = 127.0.0.1:6090
@token = 

### metadata.GetApp
GET http://{{baseURL}}/api/v1/metadata/app 
Accept: application/json

{
    "token": "{{token}}"
}

### metadata.GetAppByID
GET http://{{baseURL}}/api/v1/metadata/app/get 
Accept: application/json

{
    "id":1,
    "token": "{{token}}"
}

### metadata.GetAppByName
GET http://{{baseURL}}/api/v1/metadata/app/app-name 
Accept: application/json

{
    "app_name":"app2",
    "token": "{{token}}"
}

### metadata.GetDBsByAppID
GET http://{{baseURL}}/api/v1/metadata/app/db
Accept: application/json

{
    "id":1,
    "token": "{{token}}"
}

### metadata.GetUsersByAppID
GET http://{{baseURL}}/api/v1/metadata/app/user
Accept: application/json

{
    "id":1,
    "token": "{{token}}"
}

### metadata.AddApp
POST http://{{baseURL}}/api/v1/metadata/app 
Content-Type: application/json

{
    "token": "{{token}}",
    "app_name": "10086",
    "level":1,
    "owner_id":1
}

### metadata.UpdateAppByID
POST http://{{baseURL}}/api/v1/metadata/app/update
Content-Type: application/json

{
    "id":16,
    "token": "{{token}}",
    "app_name": "10000",
    "level":1,
    "owner_id":1
}

### metadata.DeleteAppByID
POST http://{{baseURL}}/api/v1/metadata/app/delete 

{
    "id":14,
    "token": "{{token}}"
}

### metadata.AppAddDB
POST http://{{baseURL}}/api/v1/metadata/app/add-db
Content-Type: application/json

{
    "id":16,
    "token": "{{token}}",
    "db_id":1
}

### metadata.AppAddUser
POST http://{{baseURL}}/api/v1/metadata/app/add-user
Content-Type: application/json

{
    "id":16,
    "token": "{{token}}",
    "user_id":15
}


### metadata.AppDeleteDB
POST http://{{baseURL}}/api/v1/metadata/app/delete-db
Content-Type: application/json

{
    "id":16,
    "token": "{{token}}",
    "db_id":1
}

### metadata.AppDeleteUser
POST http://{{baseURL}}/api/v1/metadata/app/delete-user
Content-Type: application/json

{
    "id":16,
    "token": "{{token}}",
    "user_id":15
}