### alert.SendEmail
POST http://{{baseURL}}/api/v1/alert/email
Content-Type: application/json

{
    "to_addrs":"allinemailtest@163.com",
    "cc_addrs":"allinemailtest@163.com",
    "subject":"api_test_mail",
    "content":"api_test_mail"
}

