http://127.0.0.1:6090

### GetEnv
Content-Type: application/json
GET /api/v1/metadata/env

### GetEnvByID
Content-Type: application/json
GET /api/v1/metadata/env/get/2

### GetEnvByName
Content-Type: application/json
GET /api/v1/metadata/env/env-name/hi

### AddEnv
Content-Type: application/json
POST /api/v1/metadata/env
{"env_name": "61616", "del_flag": 1}

### UpdateEnvByID
Content-Type: application/json
POST /api/v1/metadata/env/update/35
{"env_name": "re1l3","del_flag": 1}

### DeleteEnvByID
Content-Type: application/json
POST /api/v1/metadata/env/delete/9
