
http://127.0.0.1:6090

### get all middleware server
Accept: application/json
GET /api/v1/metadata/middleware-server

### get middleware server by cluster id
Accept: application/json
GET /api/v1/metadata/middleware-server/cluster-id/13

### get middleware server by id
Accept: application/json
GET /api/v1/metadata/middleware-server/get/1

### get middleware server by host info
Accept: application/json
GET /api/v1/metadata/middleware-server/host-info?host_ip=3&port_num=1

### add new middleware server
Content-Type: application/json
POST /api/v1/metadata/middleware-server
{"cluster_id": 13, "server_name": "test003", "middleware_role": 1, "host_ip": "123.123.123.1", "port_num": 12}

### update middleware-server by id
Content-Type: application/json
POST /api/v1/metadata/middleware-server/update/31
{"server_name": "newTest", "del_flag": 1}


### delete middleware-server by id
Content-Type: application/json
POST /api/v1/metadata/middleware-server/delete/31
