http://localhost:6090

### GetUser
Accept: application/json
GET /api/v1/metadata/user

Accept: application/json
### GetUserByName
GET /api/v1/metadata/user/user-name/user_name

Accept: application/json
### GetUserByID
GET /api/v1/metadata/user/get/5

### GetUserByEmployeeID
Accept: application/json
GET /api/v1/metadata/user/employee-id/employee_id

### GetUserByAccountName
Accept: application/json
GET /api/v1/metadata/user/account-name/account_name

### GetUserByEmail
Accept: application/json
GET /api/v1/metadata/user/email/email

### GetUserByTelephone
Accept: application/json
GET /api/v1/metadata/user/telephone/telephone

### GetUserByMobile
Accept: application/json
GET /api/v1/metadata/user/mobile/mobile

### AddUser
Content-Type: application/json
POST /api/v1/metadata/user
 {"department_name": "department_name","employee_id": "employee_id21", "telephone": "telephone","role": 2,"del_flag": 0,"user_name": "user_name21","account_name": "account_na1me2","email": "emai12l","mobile": "mobile" }

### UpdateUserByID
Content-Type: application/json
POST /api/v1/metadata/user/update/3

  {"department_name": "department_name","employee_id": "employee_id2", "telephone": "telephone","role": 2,"del_flag": 0,"user_name": "user_name2","account_name": "account_name2","email": "emai2l","mobile": "mobile" }

### DeleteUserByID
Content-Type: application/json
POST /api/v1/metadata/user/delete/1
