### query.GetByMySQLClusterID
GET http://{{baseURL}}/api/v1/query/cluster
Content-Type: application/json

{
    "token": "{{token}}",
    "mysql_cluster_id": {{mysql_cluster_id}},
    "start_time": "{{startTime}}",
    "end_time": "{{endTime}}",
    "limit": {{limit}},
    "offset": {{offset}}
}

### query.GetByMySQLServerID
GET http://{{baseURL}}/api/v1/query/server
Content-Type: application/json

{
    "token": "{{token}}",
    "mysql_server_id": {{mysql_server_id}},
    "start_time": "{{startTime}}",
    "end_time": "{{endTime}}",
    "limit": {{limit}},
    "offset": {{offset}},
    "login_name": "ddd"
}

### query.GetByHostInfo
GET http://{{baseURL}}/api/v1/query/host-info
Content-Type: application/json

{
    "token": "{{token}}",
    "host_ip": "{{mysql_host_ip}}",
    "port_num": {{mysql_port_num}},
    "start_time": "{{startTime}}",
    "end_time": "{{endTime}}",
    "limit": {{limit}},
    "offset": {{offset}}
}

### query.GetByDBID
GET http://{{baseURL}}/api/v1/query/db
Content-Type: application/json

{
    "token": "{{token}}",
    "db_id": {{db_id}},
    "start_time": "{{startTime}}",
    "end_time": "{{endTime}}",
    "limit": {{limit}},
    "offset": {{offset}}
}

### query.GetByMySQLSQLID
GET http://{{baseURL}}/api/v1/query/sql
Content-Type: application/json

{
    "token": "{{token}}",
    "mysql_server_id": {{mysql_server_id}},
    "sql_id": "{{sql_id}}",
    "start_time": "{{startTime}}",
    "end_time": "{{endTime}}",
    "limit": {{limit}},
    "offset": {{offset}}
}

