### query.GetByMySQLClusterID
GET http://{{baseURL}}/api/v1/query/cluster/1
Content-Type: application/json

{
    "start_time": "{{startTime}}",
    "end_time": "{{endTime}}",
    "limit": {{limit}},
    "offset": {{offset}}
}

### query.GetByMySQLServerID
GET http://{{baseURL}}/api/v1/query/server/1
Content-Type: application/json

{
    "start_time": "{{startTime}}",
    "end_time": "{{endTime}}",
    "limit": {{limit}},
    "offset": {{offset}}
}

### query.GetByDBID
GET http://{{baseURL}}/api/v1/query/db/1
Content-Type: application/json

{
    "mysql_server_id": 1,
    "start_time": "{{startTime}}",
    "end_time": "{{endTime}}",
    "limit": {{limit}},
    "offset": {{offset}}
}

### query.GetByMySQLSQLID
GET http://{{baseURL}}/api/v1/query/F9A57DD5A41825CA
Content-Type: application/json

{
    "mysql_server_id": 1,
    "start_time": "{{startTime}}",
    "end_time": "{{endTime}}",
    "limit": {{limit}},
    "offset": {{offset}}
}

