### sqladvisor.GetFingerprint
GET http://{{baseURL}}/api/v1/sqladvisor/fingerprint
Content-Type: application/json

{
    "token": "{{token}}",
    "sql_text": "select * from a where id = 1;"
}


### sqladvisor.GetSQLID
GET http://{{baseURL}}/api/v1/sqladvisor/sql-id
Content-Type: application/json

{
    "token": "{{token}}",
    "sql_text": "select * from a where id = 1;"
}

### sqladvisor.Advise
POST http://{{baseURL}}/api/v1/sqladvisor/advise
Content-Type: application/json

{
    "token": "{{token}}",
    "db_id": {{db_id}},
    "sql_text": "select * from t_meta_db_info where create_time<'2021-01-01';"
}